### ISSUE TITLE
The "quirks of miniboxing" meta-bug

### ISSUE THREAD

**Issue by VladUreche** [miniboxing/miniboxing-plugin#137]
The quirks of miniboxing are pretty much the same as for specialization: http://axel22.github.io/2013/11/03/specialization-quirks.html

**Comment by VladUreche** [comment]
The quirks of specialization:
- [x] 1.1 "Know the conditions for method specialization" - method speciaization - fixed by miniboxing
- [x] 1.2 "Know the conditions for method specialization" - class specialization - fixed by miniboxing
- [x] 2. "Initialize specialized values outside constructor body" - fixed by #64 #105
- [ ] 3. "Resolve access problems using the package-private modifier" - **TODO:** warnings are produced, but maybe this could be improved #136 
- [x] 4. "Use traits where possible" - fixed by design in miniboxing
- [x] 5. "Avoid traits where possible" - fixed by design in miniboxing
- [x] 6. "Make your classes as flat as possible" - proper warning issued
- [x] 7. "Avoid super calls" - fixed by bug #166 
- [x] 8. "Be wary of vars" - fixed by design in miniboxing
- [x] 9. "Think about the primitive types you really care about" - fixed by design in miniboxing
- [ ] 10. "Avoid using specialization and implicit classes" - **TODO:** need to investigate
